export type Language = "zh" | "en";

const simplifiedChinese: Record<string, string> = {
  "Jev Send Check": "Jev 发送前检查",
  "Choose your audience and goals, check the tone, then compare, edit, and copy your message.":
    "选好沟通对象和表达目标，检查语气，再对照修改、复制发送。",
  "Try: Please send me the report today. Let me know if you need more time.":
    "试试：麻烦今天把报告发给我，如果需要更多时间请告诉我。",
  "Who is this for?": "发给谁？",
  "Choosing an audience sets suggested goals. You can adjust them.": "选择沟通对象会设置推荐目标，也可以自行调整。",
  "Communication goals": "表达目标",
  "Treat checks as suggestions. Drafts go to Vercel AI Gateway for analysis after typing pauses.": "检查结果仅供参考。输入暂停后，草稿会发送至 Vercel AI Gateway 分析。",
  "Colleague / collaborator": "同事 / 合作伙伴",
  "Teacher / manager": "老师 / 上级",
  Client: "客户",
  "Friend / family": "朋友 / 家人",
  "Copy current text": "复制当前文本",
  Copied: "已复制",
  "Copy unavailable. Select the text and press Cmd/Ctrl+C.": "无法自动复制，已选中文字，请按 Cmd/Ctrl+C。",
  "Analyze again": "重新分析",
  "View full analysis": "查看全部分析",
  "Goal checks": "目标检查",
  "Sound polite": "表达礼貌",
  "Make a request": "提出请求",
  "Invite a reply": "引导对方回复",
  "Make urgency clear": "表达紧迫感",
  "Keep urgency low": "弱化紧迫感",
  "Use a formal tone": "使用正式语气",
  "Try a courteous opening and acknowledge the other person's time.": "可以加上礼貌的开场，并照顾对方的时间安排。",
  "Name the specific action you want the other person to take.": "说清楚希望对方具体做什么。",
  "Add a clear question or ask them to confirm.": "补上一个明确的问题，或请对方确认。",
  "If it is time-sensitive, state when you need an answer or action.": "如果有时间要求，写清楚何时需要回复或完成。",
  "If timing is flexible, say so and soften words like today or immediately.": "如果时间可以商量，直接说明，并调整“今天必须”“立即”等措辞。",
  "Use complete sentences and replace slang with neutral wording.": "使用完整句子，把网络用语换成中性的表达。",
  "Choose a goal to see focused feedback.": "选择一个表达目标，查看对应建议。",
  "Looks aligned": "基本符合",
  "Consider adjusting": "可以再调整",
  Uncertain: "暂不确定",
  "Analysis unavailable": "分析暂不可用",
  "Jev is unsure here. Use your judgment.": "Jev 对这一项把握不足，请结合实际情况判断。",
  "The current wording appears to fit this goal.": "当前措辞看起来符合这个目标。",
  "Jev Mind Reader": "Jev 读心输入框",
  "Jev mind reader": "Jev 读心输入框",
  "Type anything and Jev reads it as you go. Every bar is a probability, and a faded card means Jev isn't sure.":
    "随便输入一句话，Jev 会实时分析。每根条表示一个概率，卡片越淡，说明 Jev 越不确定。",
  "Try: Wow, overtime again this weekend, I'm thrilled 🙄": "试试：哇，这周末又要加班，真是太开心了 🙄",
  "Message for Jev to read": "输入让 Jev 分析的文字",
  "Jev's readings": "Jev 的分析结果",
  Language: "语言",
  "Analysis failed": "分析失败",
  "A · Original": "A · 原句",
  "B · Rewrite": "B · 改写",
  "Current text": "当前文本",
  "Pin as original": "固定为原句",
  "Use current as original": "将当前文本设为原句",
  "End comparison": "结束对照",
  "Enter a sentence, wait for the analysis, then pin it as the original and try a rewrite.":
    "输入一句话，等分析完成后固定为原句，再尝试改写。",
  "Edit B to compare. ▲ / ▼ show increases / decreases from A, the pinned original.":
    "修改 B 即可对照。▲ / ▼ 表示相对于固定原句 A 的上升 / 下降。",

  emotion: "情绪",
  intent: "意图",
  politeness: "礼貌程度",
  urgency: "紧急程度",
  sarcasm: "反讽",
  "needs reply": "需要回复",
  formality: "正式程度",

  happy: "开心",
  angry: "愤怒",
  disappointed: "失望",
  neutral: "中性",
  other: "其他",
  ask: "提问",
  request: "请求",
  complain: "抱怨",
  share: "分享",
  chat: "闲聊",
  formal: "正式",
  casual: "日常",
  slang: "网络用语",

  rude: "粗鲁",
  direct: "直接",
  polite: "礼貌",
  "very polite": "非常礼貌",
  none: "无",
  low: "低",
  medium: "中",
  high: "高",

  choice: "分类",
  score: "评分",
  boolean: "是 / 否",
  "yes / no": "是 / 否",
  yes: "是",
  no: "否",
  "leans yes": "倾向是",
  "leans no": "倾向否",
  "probability of yes": "为“是”的概率",
  confidence: "置信度",

  "Waiting for input": "等待输入",
  "Reading…": "分析中…",
  ms: "毫秒",
  "input tokens": "输入 tokens",
  cost: "费用",
};

export function translate(language: Language, text: string): string {
  if (language === "en") return text;
  return simplifiedChinese[text] ?? text;
}
